### ISSUE TITLE
Keep only last verified address displayed 

### ISSUE THREAD

**Issue by mnugumanova** [oraclesorg/oracles-dapps-validators#86]
There is no benefit in displaying all of the addresses in this Dapp.
I want to open this issue as a ballot for other Validator to vote to find if they agree.

**Comment by 6proof** [comment]
I agree. The ONLY address that should be listed is that of the one listed in Validator MetaData by Validator, and the "Verified" or "Unverified" flag should be simple yes/no toggle base on result.  Multiple addresses should never show here.

**Comment by varasev** [comment]
For now, Validators DApp displays all registered addresses that stored in `Proof of Physical Address` smart contract.

We could display only the last confirmed address in Validators DApp but remaining addresses will still be stored in `Proof of Physical Address` smart contract and can be read by anyone until they're unregistered.

PoPA smart contract address and ABI are available in our `poa-chain-spec` repo in the `core` branch.

**Comment by phahulin** [comment]
It might be difficuly to implement what @6proof suggests as it requires integration between DApps.

@mnugumanova is it because one of the addresses is "expired" (you relocated/etc)? In this case you can delete it from PoPA Dapp by going into "My addresses" and clicking on a trash icon, this will cost some small amount of POA for tx fee.

**Comment by mnugumanova** [comment]
It worked. Thanks for the guidance
